# Generated by Django 4.0.4 on 2022-05-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputtedwaittime',
            name='accuracy',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='inputtedwaittime',
            name='point_value',
            field=models.IntegerField(default=10),
        ),
    ]
