# Generated by Django 4.0.4 on 2022-05-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_restaurant_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputtedwaittime',
            name='wait_length',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
