# Generated by Django 4.0.3 on 2022-03-21 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_restaurantmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='yelp_page',
            field=models.URLField(blank=True),
        ),
    ]
