# Generated by Django 4.0.4 on 2022-05-03 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_restaurant_phone_number_restaurant_website_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputtedWaittimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wait_length', models.IntegerField()),
                ('accuracy', models.FloatField()),
                ('point_value', models.IntegerField()),
                ('reporting_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inputs', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waittimes', to='api.restaurant')),
            ],
        ),
    ]
