# Generated by Django 4.0.4 on 2022-05-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_restaurant_user_who_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='credibility_rating',
            field=models.FloatField(default=0),
        ),
    ]
