# Generated by Django 4.0.4 on 2022-05-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_appuser_credibility_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
