# Generated by Django 4.0.4 on 2022-05-12 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
