# Generated by Django 4.0.4 on 2022-05-04 02:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_appuser_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='credibility_rating',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='points',
        ),
        migrations.AddField(
            model_name='inputtedwaittimes',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inputtedwaittimes',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 5, 4, 2, 45, 18, 129209)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inputtedwaittimes',
            name='seated_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 5, 4, 2, 45, 40, 867181)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inputtedwaittimes',
            name='wait_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='yelp_page',
            field=models.URLField(blank=True, null=True),
        ),
    ]
