# Generated by Django 4.0.4 on 2022-05-04 17:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_inputtedwaittimes_inputtedwaittime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputtedwaittime',
            name='arrival_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
