# Generated by Django 4.0.4 on 2022-05-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_inputtedwaittime_wait_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputtedwaittime',
            name='wait_length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
