# Generated by Django 4.0.4 on 2022-05-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_appuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
