# Generated by Django 4.0.4 on 2022-05-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_restaurant_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
