# Generated by Django 4.0.4 on 2022-05-12 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_alter_address_id_alter_country_id_alter_locality_id_and_more'),
        ('api', '0008_alter_restaurant_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='address.address')),
            ],
            bases=('address.address',),
        ),
    ]
